### ISSUE TITLE
2016.3.1 Installer does not prompt for Proxy settings when network is disconnected.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-player-electron#10]
**How to recreate**
1. Download newest installer
2. Pull network cable (ensure that no wireless is connected)
3. Start installer 2016.3.1
4. Wait for main UX, press continue.

**What happens**
The installer closes, nothing further happens.

**What I expect to happen**
The Proxy configuration page should appear.

Windows 7 x32/64 & Windows 10 x64
Ubuntu 14.04 x64

**Comment by tejohnso** [comment]
@btfrise The proxy settings only show up on initial install.  
If you hadn't completely removed any previous install the settings won't show up.

**Comment by btfrise** [comment]
@tejohnso This happens on a fresh install.

**Comment by hcs0** [comment]
@btfrise I've edited the original to include Ubuntu 14.04 x64

**Comment by robb-price** [comment]
This was fixed with an updated Installer on both Windows and Linux.
