### ISSUE TITLE
2016.3.1 Installer gives double unknown error message when network is disconnected.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-player-electron#11]
**How to recreate**
1. Download newest installer
2. Pull network cable (ensure that no wireless is connected)
3. Start installer 2016.3.1
4. Wait for main UX, press continue.

**What happens**
The installer shows two unknown error messages

**What I expect to happen**
The Proxy configuration page should appear.

Ubuntu 14.04 x64

**Comment by robb-price** [comment]
This is fixed with the new installer given to us March 2.
