### ISSUE TITLE
2016.3.1 Installer - Pressing Restart Player on the Displays page does not restart the Player

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-player-electron#12]
**How to recreate**
1. Install Rise Player using the 2016.3.1 installer
2. Add a display ID
3. Press restart player on the display page

**What happens**
Player does not restart

**What should happen**
Player should restart

Windows 7 x32/x64, Windows 10 x64, Ubuntu 14.04 x64

**Comment by fjvallarino** [comment]
@btfrise Could you check if RisePlayer.ver is on version 2016.02.24.13.00? It's deployed in the latest channel, so you may not have it.

**Comment by btfrise** [comment]
@fjvallarino How would I check that? This machine does not have Rise Player installed, therefore no display ID. This is a fresh install from the 2016.3.1 installer.

**Comment by fjvallarino** [comment]
@btfrise In the rvplayer directory you should have a RisePlayer.ver file

**Comment by btfrise** [comment]
@fjvallarino There is no RisePlayer.ver file. It does not fully install. There are only two files, installer-detail.log and installer-events.log.

**Comment by fjvallarino** [comment]
@btfrise Does the display even start? You should have something similar to this:

![image](https://cloud.githubusercontent.com/assets/6565497/13441734/869d0826-dfd7-11e5-86fb-b19d4e3781be.png)

**Comment by hcs0** [comment]
@fjvallarino @btfrise 

I see the Restart Player button does not work for Ubuntu 14.04.  Doing a BQ of the DisplayID (A9XGBQR5NXTP), it states that Installer version is 2016.3.1.15.18

**Comment by fjvallarino** [comment]
@btfrise @hcs0 For this issue what's important is Player's version, not Installer's, since Player is the one in charge of restarting/rebooting the display. The Player version which fixes this issue is 2016.02.24.13.00.

**Comment by hcs0** [comment]
@fjvallarino @btfrise Useful to know!

It's RisePlayer 2016.02.11.21.00 also

**Comment by fjvallarino** [comment]
@btfrise @hcs0 Since this fix is, for the moment, on latest channel, you will have to restart your installer a few times before it picks this new version up. Although, considering we're at 2% rollout, I'd suggest manually replacing Player with this one http://install-versions.risevision.com/RisePlayer-2016-02-24-13-00.zip (otherwise you may end up restarting about 50 times before getting the right version)

**Comment by btfrise** [comment]
@fjvallarino Thanks. I'll test and let you know.

**Comment by tejohnso** [comment]
Also @btfrise CS already tested that functionality with that player version, so I don't think you need to re-test it. 
But If you're wanting to confirm that the installer properly upgrades via the rollout percentage, you can keep restarting it from rvplayer/Installer/installer and if it doesn't start downloading components you know it didn't hit the percentage and you can quit it immediately and retry.

**Comment by btfrise** [comment]
@tejohnso @fjvallarino understood. I've tested with the version that Francisco recommended above and it worked.

FYI @robb-price I think we need to improve our testing. We did not take this situation into account.

**Comment by btfrise** [comment]
@tejohnso @fjvallarino both Robb and I have tested copying the new RisePlayer.jar from http://install-versions.risevision.com/RisePlayer-2016-02-24-13-00.zip in Ubuntu 14.04 x32/x64.

- Install newest Rise Installer
- Assign DisplayID
- Close player
- Kill Java
- Copy over RisePlayer-2016-02-24-13-00.jar to /Home/rvplayer
- Reboot

When player opens, the new player version is not reflected on the Displays page.

**Comment by robb-price** [comment]
@btfrise @tejohnso @fjvallarino Also, the most important thing, is the Restart Player functionality doesn't work, even after copying the file over, likely because it is still the older version of Player.

**Comment by fjvallarino** [comment]
@robb-price @btfrise Just to be sure: are you removing the existing RisePlayer.jar and then renaming RisePlayer-2016-02-24-13-00.jar to RisePlayer.jar?

**Comment by btfrise** [comment]
@fjvallarino When I extract the file from the .zip, it is already named RisePlayer.jar

**Comment by fjvallarino** [comment]
@robb-price @btfrise I just made a clean install, replaced RisePlayer.jar and restarted from Displays App and it worked correctly (using this display id: Q2MNN6WRHSRC). Core may not send the message immediately (it took three seconds in one case, over a minute in another).

**Comment by btfrise** [comment]
Went through this with Tyler, Robb, and Francisco. Restart Player works with new player jar file. We are not seeing the updated player version because we are using a workaround to install the new RisePlayer.jar. When RisePlayer.jar is installed through the installer, it will reflect the new versions on displays.risevision.com.
