### ISSUE TITLE
2016.3.1 Installer - Edit Rise Player Configuration does not appear

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-player-electron#13]
**How to recreate**
1. Install Rise Player using the 2016.3.1 installer
2. Close Rise Player
3. Click the Start Menu
4. Click the Rise Vision folder

**What happens**
There is no Edit Rise Player Configuration option.

**What should happen**
There should be an Edit Rise Player Configuration option.

Windows 7 x32/x64, Windows 10 x64, Ubuntu x64

**Notes**
If upgrading from existing v2 installation, no Edit Rise Player Configuration option appears.
If upgrading from existing v3 installation, Edit Rise Player Configuration DOES appear.
In Ubuntu 14.04, if you click the Unity button at the top left and search for Rise Player, Edit Rise Player Configuration does not appear.

**Comment by tejohnso** [comment]
@btfrise Edit Configuration has been removed.  The one you're seeing from existing v3 is probably the one that was previously added.

**Comment by btfrise** [comment]
FYI @robb-price @hcs0 Apparently edit configuration has been removed.
