### ISSUE TITLE
Presentations are able to be zoomed with Pinch to Zoom.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-player-electron#14]
**How to recreate**
1. Add any presentation to an interactive Windows 10 display
2. Pinch the presentation

**What happens**
Pinch to zoom allows zooming into portions of the presentation

**What should happen**
Pinch to zoom should not function within player

**Notes**
We see this on every presentation, but it was initially noticed in this donor wall http://rva.risevision.com/#/PRESENTATION_MANAGE/id=adbcf629-3904-4cab-949b-05f8de6cfd0e?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

OS: Windows 10 x64, Ubuntu 14.04 x64
Player version: 2016.03.03.13.00 
Chrome version: Chrome 48.0.2564.116, Chrome 49.0.2623.87

**Comment by ahmedalsudani** [comment]
@btfrise just for clarification, this did not happen during installation. It was after the display had loaded, correct?

**Comment by ByronDarlison** [comment]
@ahmedalsudani curious, do we have the ability to disable pinch to zoom on chrome? And do you know if it can't be done with the electron browser more easily? Thanks!

**Comment by ahmedalsudani** [comment]
@ByronDarlison I believe there's an HTML attribute that can be set to disable zooming in.

It works on mobile devices, but I have never tried it on a desktop browser. I imagine it would work.

If it does work on a desktop browser, I'm not sure how easy it would be to fix this issue. We have to experiment with `iframes` and zooming in because my understanding is that viewer makes some use of those, and this issue would probably need to be solved on the viewer side.

**Comment by ByronDarlison** [comment]
@ahmedalsudani thanks! @mmeiers @pcsandford @sheadarlison you guys have any thoughts on this? Thanks

**Comment by mmeiers** [comment]
@ahmedalsudani @btfrise @ByronDarlison 
I think something has to be added to the viewport. I wonder if this would work.

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

Perhaps we need discuss some sort of global html import that covers this and a few other items like right clicking that is added to all interactive (or better yet all presentations by default).

**Comment by mmeiers** [comment]
@btfrise I added to that presentation, can you see if that resolved it?

**Comment by ByronDarlison** [comment]
@mmeiers thanks. @btfrise @robb-price to confirm, this wasn't happening with Windows 7 and previous Chrome, is that correct?

**Comment by robb-price** [comment]
@ByronDarlison We did see this on Chrome 47, but @btfrise does not recall if this was present on Win 7 or not. I will be testing the Presentation that @mmeiers fixed after Scrum of Scrums.

**Comment by mmeiers** [comment]
@robb-price @ByronDarlison I could not replicate on windows 7.

**Comment by ByronDarlison** [comment]
@mmeiers to confirm, you can pinch to zoom on win 10 with chrome 48 and you can't on win 7 with chrome 48, is that right?

**Comment by mmeiers** [comment]
@ByronDarlison The only windows machine I have here at home is windows 7 and was not able to replicate. Id have to go into plex to test windows 10.

**Comment by ByronDarlison** [comment]
@mmeiers okay. @robb-price let us know the conclusion. Thanks

**Comment by robb-price** [comment]
@ByronDarlison @ahmedalsudani @mmeiers Can confirm that this still happens on Windows 10. This quick video helps show the issue: https://www.dropbox.com/s/9pdui3fu3899oll/VID_20160309_112058.mp4?dl=0

**Comment by ahmedalsudani** [comment]
Thanks @robb-price. It seems to me like there is simply no workaround around zooming in. We need to figure out whether it's an issue though so we can be on the lookout for a solution when we transition to Electron.

I figured I'd try zooming in on the installer and this happened:

![One thing I found through a test](https://cloud.githubusercontent.com/assets/606185/13643090/27da901c-e5ed-11e5-9f32-1c0267fe2f29.png)

Looking into disabling the touchscreen pinch APIs in Electron, but I'm not holding my breath since it uses the same engine as Chrome.

**Comment by ahmedalsudani** [comment]
@btfrise @ByronDarlison good news and somewhat bad news.

The bad news is there's no way to fix this on Chrome.

The good news is that it's fixable in Electron. I fixed it in the Installer window, so when we move presentations to Electron, we can disable pinch-to-zoom in presentations.

**Comment by alanclayton** [comment]
@robb-price you think the pinch to zoom is an win10 thing given it doesn't happen in win7? http://www.cnet.com/how-to/how-to-disable-the-pinch-zoom-gesture-on-windows-laptops/

**Comment by robb-price** [comment]
@alanclayton Yeah, it's a Win 10 thing only, for that exact reason. That setting in your URL would be a great way to fix in the case someone is suffering the issue on Win 10. Just have to make sure it works.

**Comment by tejohnso** [comment]
@robb-price @alanclayton I wonder if that configuration can be applied to any touch screen so the decision to disable pinch-to-zoom could be made on the hardware.  And if so, is that how we'd want to deal with this?  I'm still not sure we'd want to force it on every browser window / presentation even if we could.

**Comment by robb-price** [comment]
@tejohnso @alanclayton The only issue I foresee is what if you don't want Pinch to zoom, and your hardware is unsupported with that fix outlined above. Then you are SOL.

@ahmedalsudani states that this can be fixed in the Electron browser, once that is available, maybe we can have this as a Presentation option, similar to Hide Mouse Pointer settings?

**Comment by alanclayton** [comment]
@robb-price have you tested that disabling pinch to zoom in win10 fixes the issue? If so, why don't we just have that ready as an option for users who experience the issue and if this becomes a bigger problem then look at fixing in electron.

**Comment by robb-price** [comment]
@alanclayton Will test and update this card with the results.

**Comment by mmeiers** [comment]
@alanclayton agreed i think that would be the best route until we know more. I literally had someone ask today to enable pinch zoom so they could zoom in on images.

**Comment by btfrise** [comment]
@alanclayton @mmeiers @robb-price The instructions that Alan presented are hardware specific. This screenshot (http://www.screencast.com/t/dXpAflDgLzTV) displays the mouse configuration of a Samsung IR Overlay. Windows sees the Samsung Overlay as just another HID Compatible Mouse, with no configuration options for multitouch.

Samsung does not offer any configuration utility or driver for the IR Overlay.

**Comment by btfrise** [comment]
I noticed while testing interactive today that this is also present on Ubuntu 14.04 x64.

**Comment by robb-price** [comment]
@ByronDarlison @alanclayton @ahmedalsudani CS did not discover any reliable way to remove the ability to Pinch and Zoom on the OS settings on either Windows or Linux 14.04 64 bit.

**Comment by btfrise** [comment]
I've further tested some method of disabling pinch to zoom.

Installed synaptics configuration utility in an effort to use their disable Pinch to Zoom option. The synaptics utility does not recognize Samsung overlays.

I tried variations of an HTML meta tag `<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">` in a presentations. None worked.

I tried using chrome://flags/#enable-pinch to disable. I disabled the flag in player's chrome, saved changes, launched player, re-launched player's chrome. The setting was kept, but pinch to zoom still functioned on Rise Player.

I called Samsung, and they have no driver or configuration utility available for their Overlay.

**Comment by ByronDarlison** [comment]
To confirm, this issue is being corrected with the electron renderer, do I have that right?

And @tejohnso do we have this issue queued and on a card in an applicable epic to resolve it?

Thanks

**Comment by tejohnso** [comment]
The card is over to Byron now as discussed in standup.

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;I38fAjZ9&#x2F;995-pinch-to-zoom-issue-2"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Pinch to zoom issue [2]</a>

**Comment by ByronDarlison** [comment]
@tejohnso @fjvallarino can you confirm this issue is now fixed and if fixed @mmeiers @btfrise could you confirm and close the issue? Thanks

FYI @sheadarlison

**Comment by fjvallarino** [comment]
@ByronDarlison yes, it was deployed to production on Friday, and it's currently being rolled out at 2%

**Comment by ByronDarlison** [comment]
@fjvallarino thanks! @btfrise @mmeiers can you confirm and close. Thanks

**Comment by mmeiers** [comment]
@btfrise is going to test today.
FYI @ByronDarlison @fjvallarino

**Comment by btfrise** [comment]
@ByronDarlison Looks good! I'm closing this issue.
