### ISSUE TITLE
URL's with the username and password in them have stopped working.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-player-electron#30]
<b>How it works now:</b>
A recent change in Google Chrome stopped URL's that had the username/password embedded from working: https://www.chromestatus.com/feature/5669008342777856. 

One User (so far) has reported that this is also occurring in Player, where they were previously able to see the URL in a Schedule, they now cannot, and they see either of these errors in the Dev Console: https://drive.google.com/file/d/1Gy-57Jp1fdMjOQJQPCyBMDMnTzH22J0W/view or https://goo.gl/3a7kTV

After speaking with Tyler, this isn't so much a bug as a possible enhancement so users could continue to use these types of URL's in their Schedules. 

Example of a Schedule that uses this: https://apps.risevision.com/schedules/details/46631474-9fd2-4eef-8240-386668af03ea?cid=556323b8-984c-4127-aa08-4d73d019bcb8

**Comment by tejohnso** [comment]
https://trello.com/c/JQASbNDt
