### ISSUE TITLE
Installer causes Windows Disk Usage to Spike to 100%, and installs take 5+ minutes.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-player-electron#7]
How to recreate:
Perform a fresh install of Rise Player on Windows 10 x32 or x64.

What happens:
Disk usage pegs to 100% throughout install, and installs can take 5+ minutes (I timed mine at 7:32). The installer really seems to struggle at three points,
- Extracting (Before full UX loads)
- Extracting Components
- Installing Launcher

See screenshot http://www.screencast.com/t/nFBpflUPGDCg
See video of installation here http://www.screencast.com/t/kYk01RZ7qVg

Windows 10 32bit & 64bit

**Comment by tejohnso** [comment]
Investigating https://trello.com/c/EsE7Uncb

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;EsE7Uncb&#x2F;857-issue-investigate-self-extraction-process-1"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [ISSUE] Investigate self extraction process [1]</a>

**Comment by btfrise** [comment]
Was not able to replicate with the 2016.3.1 installer through multiple attempts. Closing.
