### ISSUE TITLE
Weather Widgets cause Chrome "Allow/Decline Know your location" message.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-player-electron#8]
How to recreate this issue:

1. Install Rise Player on any Windows/Linux media player.
2. Add the Display ID KSWMFJK7Z4HF

When the player starts up, you will see the following error message http://www.screencast.com/t/BhIYM2kGaK 

Selecting "Allow" will not persist through closing/opening of player. Changing the Location setting (http://www.screencast.com/t/nCpdrTXej6Y) in Chrome Privacy Settings will not persist through opening/closing of Chrome.

This happens with the deprecated Rise Weather Widget when set to geolocation as well.

**Comment by tejohnso** [comment]
@alanclayton @rodrigopavezi This seems like a content issue rather than installer / player related.

**Comment by alanclayton** [comment]
@tejohnso Isn't this a browser configuration issue? By default we want Chrome to allow geolocation reporting without a user manually having to do anything.

**Comment by tejohnso** [comment]
@fjvallarino Do you know if we have a flag for that?   If we do, why did it stop working?

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;S9KyKQpz&#x2F;859-issue-8-geolocation-issue-on-weather-widget-3"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Issue 8 Geolocation issue on weather widget [3]</a>

**Comment by ByronDarlison** [comment]
Possible Chrome issue, will address as part of installation improvement epic

**Comment by ByronDarlison** [comment]
@btfrise can you confirm if this is still valid? Does this problem continue to occur? Thanks

**Comment by ByronDarlison** [comment]
@robb-price @btfrise @alex-deaconu is this issue still valid? I am wondering if it is solved given we can't recreate the problem we had with this issue https://github.com/Rise-Vision/viewer/issues/67 and we closed it yesterday. Can you let me know. Thanks!

**Comment by alex-deaconu** [comment]
@ByronDarlison I don't believe this is related to #67, in that instance the address was obtained from the Core, not geolocation. However I may be mistaken. Thanks.

**Comment by ByronDarlison** [comment]
@alex-deaconu okay. Thanks. @robb-price @btfrise do either of you know if this issue still exists? Thanks

**Comment by robb-price** [comment]
@ByronDarlison @alex-deaconu We are retesting and will let you know shortly.

**Comment by robb-price** [comment]
@ByronDarlison @alex-deaconu I cannot recreate this with the Digichief Weather Widget, or our deprecated Weather Widget, using the Electron Browser. 

It has manifested itself differently in Chrome 50: We are no longer getting the box on top of the Presentation, instead the Dev Tools shows the error "Unable to obtain Geolocation Position", and nothing shows in the Widget: 
![2016-04-28_09-57-13](https://cloud.githubusercontent.com/assets/6862256/14888320/bf31aa70-0d27-11e6-9a12-eaebffa4d492.png)

This only occurs with Geolocation, and in Chrome.

**Comment by robb-price** [comment]
@alex-deaconu @ByronDarlison I don't think this is a Player issue, it should be moved to the viewer repo. Do you agree?

**Comment by ByronDarlison** [comment]
Resolved by electron chromium
