### ISSUE TITLE
Linux Installer does not automatically start Rise Player when upgrading from ver2 installer.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-player-electron#9]
**How to recreate**
1. Delete all instances of Rise Player on an Ubuntu Machine
2. Download ver2 installer
3. Download ver3 installer
4. Run ver2 installer, once player loads add display ID
5. Alt+Tab to terminal, run ver3 installer without closing player (chrome/java)

**What happens**
Player does not start automatically after ver3 installation is complete.

**What should happen**
Player should start automatically after ver3 installation is complete

**Notes**
Ubuntu 14.04LTS 64bit
Player will start and operate normally if started manually, or the media player is rebooted.

**Comment by btfrise** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5f4VW7RS&#x2F;1397-2-installer-testing-on-ubuntu-14-04-64-bit"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (2) Installer Testing on Ubuntu 14.04 64 Bit</a>

**Comment by hcs0** [comment]
verified on the new installer for Ubuntu 14.04 x32 x64

**Comment by ahmedalsudani** [comment]
This has been fixed and verified
